### ISSUE TITLE
Flutter 3.29.0 support

### ISSUE THREAD

**Issue by maryannabt** [emz-hanauer/dart-cryptography#3]
After upgrading to Flutter 3.29.0, the production build fails:

**e: file:///Users/builder/.pub-cache/hosted/pub.dev/cryptography_flutter-2.3.2/android/src/main/kotlin/dev/dint/cryptography_flutter/CryptographyFlutterPlugin.kt:24:48 Unresolved reference: Registrar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cryptography_flutter:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details**

This is because the API 'import io.flutter.plugin.common.PluginRegistry.Registrar' has been removed from the Flutter latest version. 

Will the cryptography package be updated to work with Flutter 3.29.0?

**Comment by petrleocompel** [comment]
Yes we are planning upgrade to Flutter 3.29 in next weeks. We can keep this issue to keep track of it.

**Comment by petrleocompel** [comment]
@maryannabt I noticed just now `cryptography_flutter-2.3.2` is not this library that is the old version from `devint`.
We took over as [cryptography_flutter_plus v2.3.4](https://github.com/emz-hanauer/dart-cryptography/releases/tag/v2.7.1-1)

So... I understand that this library might not be supporting Flutter 3.29.0 but you are not using this library. 
Please change your dependencies and try again.

**Comment by petrleocompel** [comment]
This issue was in my test invalid. The library does no need any changes for support of Flutter 3.29. 
If you have different result feel free to reopen.

Also since there was no activity I am closing this issue @maryannabt.
